name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libopenblas-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch==2.5.1 --index-url https://download.pytorch.org/whl/cpu
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-cov pytest-xdist pytest-timeout

    - name: Verify structure
      run: |
        echo "Current directory:"
        pwd
        echo "Directory structure:"
        ls -la
        echo "Core structure:"
        ls -la core/ || echo "No core directory"
        echo "Tests location:"
        find . -name "test_*.py" -type f | grep -v __pycache__ || echo "No tests found"

    - name: Run core tests
      run: |
        if [ -d "core/qcmd_ecs/tests" ]; then
          pytest core/qcmd_ecs/tests/ -v --cov=core/qcmd_ecs/core --cov-report=xml --cov-report=term --timeout=300
        else
          echo "ERROR: Test directory not found"
          exit 1
        fi
      continue-on-error: false

    - name: Test imports
      run: |
        python -c "from core.qcmd_ecs.core import manifold, dynamics, types; print('Core imports successful')"
        python -c "from core.models import score_model, surrogate; print('Model imports successful')"

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      if: matrix.python-version == '3.10'
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  integration-test:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test manifold operations
      run: |
        python -c "
        import torch
        from core.qcmd_ecs.core.manifold import project_to_tangent_space, retract_to_manifold
        from core.qcmd_ecs.core.types import DTYPE
        
        # Test Stiefel manifold operations
        m, k = 32, 8
        U = torch.randn(m, k, dtype=DTYPE)
        U, _ = torch.linalg.qr(U)
        
        gradient = torch.randn(m, k, dtype=DTYPE)
        U_tangent = project_to_tangent_space(U, gradient)
        U_new = retract_to_manifold(U + 0.01 * U_tangent)
        
        # Verify orthonormality
        eye_k = torch.eye(k, dtype=DTYPE)
        assert torch.allclose(U_new.T @ U_new, eye_k, atol=1e-9)
        print('✓ Manifold operations validated')
        "

    - name: Test dynamics pipeline
      run: |
        python -c "
        import torch
        from core.qcmd_ecs.core.dynamics import run_reverse_diffusion
        from core.qcmd_ecs.core.types import DTYPE
        
        # Minimal diffusion test
        m, k = 16, 4
        
        def dummy_score(U):
            return torch.randn_like(U)
        
        def dummy_energy(U):
            return torch.randn(U.shape[0])
        
        U_0 = torch.randn(m, k, dtype=DTYPE)
        U_0, _ = torch.linalg.qr(U_0)
        
        results = run_reverse_diffusion(
            score_model=dummy_score,
            energy_gradient_model=dummy_energy,
            U_T=U_0,
            num_steps=5,
            dt=1e-3
        )
        
        assert 'samples' in results
        print('✓ Diffusion pipeline validated')
        "

  style-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install linting tools
      run: |
        pip install black flake8 isort mypy

    - name: Check code formatting (Black)
      run: |
        if [ -d "core" ]; then
          black --check core/ --line-length 100 || echo "Code formatting issues detected"
        else
          echo "Skipping: core directory not found"
        fi
      continue-on-error: true

    - name: Check import sorting (isort)
      run: |
        if [ -d "core" ]; then
          isort --check-only core/ --profile black || echo "Import sorting issues detected"
        else
          echo "Skipping: core directory not found"
        fi
      continue-on-error: true

    - name: Lint with flake8
      run: |
        if [ -d "core" ]; then
          flake8 core/ --max-line-length=100 --extend-ignore=E203,E501,W503 --count || echo "Linting issues detected"
        else
          echo "Skipping: core directory not found"
        fi
      continue-on-error: true
